openapi: 3.0.0
info:
  version: 1.0.1
  title: LUDO
  description: Välkommen till Fia med Knuff
paths:
  /ludo/getallgames:
    get:
      summary: list of LUDU-games avaliable
      operationId: GetAllGames
      responses:
        '200':
          description: Success
          
  /ludo/createnewgame:
    post:
      summary: Create a new game
      operationId: CreateNewGame
      responses:
        '200':
          description: Success
          
  /ludo/{id}/getgamedetails:
    get:
      summary: details about the game, positioning of the pieces, colors in play.
      operationId: GetGameDetails
      parameters:
        - name: id
          in: path
          description: The id of the game.
          required: true
      responses:
        '200':
          description: Success
          
  /ludo/{id}/changeplayerdetails:
    put:
      summary: Change name or color on player. color change only possible in game state NotStarted.
      operationId: ChangePlayerDetails
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
      - name: oldColorID
        in: path
        required: true
      - name: Name
        in: query
        required: true
        description: updates player name.
      - name: ColorID
        in: query
        required: true
        description: updates player color.   
      
  /ludo/{id}/endturn:
    put:
      summary: Ends a players turn.
      operationId: endturn
      response:
        '200':
          description: Ended players turn.
          
  /ludo/{id}/getwinner:
    get:
      summary: Gets the winner.
      operationId: getwinner
      response:
        '200':
          description: Successful request
          
  /ludo/{id}/removegame:
    delete:
      summary: Remove this game.
      operationId: RemoveGame
      parameters:
        - name: id
          in: path
          description: The id of the game to delete.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success, you've deleted the game
          
  /ludo/{id}/rolldice:
    get:
      summary: Rolls the dice
      operationId: rolldice
      response:
        '200':
          description: Dice has been rolled.
          
  /ludo/{id}/startgame:
    put:
      summary: Starts the game.
      operationId: startgame
      parameters:
        - name: id
          description: gameID
          in: path
          required: true
      response:
        '200':
          description: Game started.
        
  /ludo/{id}/movepiece:
    put:
      summary: change positioning of a piece
      operationId: MovePiece
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        description: The id of the game to update.
        required: true
        schema:
          type: string
      - name: pieceID
        in: query
        description: ID of one specific piece.            
        required: true
        schema:
          type: int
      - name: numberOfFields
        in: query
        description: How many steps.
        required: true
        scema:
          type: int
          
  /ludo/{id}/players:
    get:
      summary: get details about player
      operationId: GetPlayerDetails
      parameters:
      - name: id
        in: path
        required: true
      - name: colorID
        in: query
        required: true
      responses:
        '200':
          description: Success
    delete:
      summary: remove player.
      operationId: RemovePlayer
      parameters:
      - name: id
        in: path
        required: true
      - name: colorID
        in: path
        required: true
      responses:  
        '200':
          description: Success
          
  /ludo/{id}/players/getallplayers:
    get:
      summary : list players in this game
      operationId: GetAllPlayers
      parameters:
      - name: id
        in: path
        description: The id of the game to retrieve all players from.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success, here's your list of players.
          
  /ludo/{id}/players/addplayer:
    post:
      summary: add new player, only applicable if game state is NotStarted
      operationId: AddPlayer
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        description: Add player to a game with this ID.
        required: true
      - name: playerName
        in: query
        description: Name of the player
        required: true
      - name: PlayerColor
        in: query
        description: playingcolor of the new player.
        required: true
